import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPresentationSnapshot,type PresentationEngine} from '../src/presentation-snapshot.js';
import {canonicalRead,canonicalReadIndependent,type CanonicalReadAdapter,type CanonicalReadAdapters,type CanonicalReadRecord} from '../src/canonical-read.js';

const record=(engine:PresentationEngine,state:'SELECTED'|'SUPERSEDED'|'REJECTED'='SELECTED',kind:'ORDINARY_CANONICAL'|'EXCEPTION_CANONICAL'='ORDINARY_CANONICAL'):CanonicalReadRecord=>{
  const run_id=`${engine}-run`,result_id=`${engine}-result`,checkpoint_id=`${engine}-cp`;
  return {contract_version:'P0_12_CANONICAL_READ_V1',engine,trading_date:'2026-09-28',canonical_type:kind,canonical_timestamp:kind==='EXCEPTION_CANONICAL'?'2026-09-28T10:05:00+05:30':'2026-09-28T09:12:00+05:30',run_id,result_id,recommendation_id:engine==='EDGE_STOCKS'?'LTF-rec':null,checkpoint_id,selection_state:state,analytical_fields:{direction:'UP',zone:[1,2]},component_records:[{name:'market',status:'VERIFIED'}],evidence_lineage:[{source:'auction'}],execution_plan:null,outcome_checkpoints:[],efficacy:null,core_shadow_lineage:engine==='IPO_EDGE'?null:{horizons:['D','D+1','D+2','D+3','D+4']},presentation_snapshot:buildPresentationSnapshot({engine,run_id,result_id,checkpoint_id,governance_state:state,sections:[{name:'summary',status:'VERIFIED'}],source_payload_hash:`${engine}-source`})};
};
const adapter=(value:CanonicalReadRecord|null):CanonicalReadAdapter=>async()=>value;
const adapters=(overrides:Partial<CanonicalReadAdapters>={}):CanonicalReadAdapters=>({5DR:adapter(record('5DR')),EDGE_STOCKS:adapter(record('EDGE_STOCKS')),IPO_EDGE:adapter(record('IPO_EDGE')),...overrides});

test('normal exact NIFTY canonical returns immutable presentation identity',async()=>{const out=await canonicalRead({engine:'5DR',trading_date:'2026-09-28',run_id:'5DR-run'},adapters());assert.equal(out.ok,true);if(out.ok)assert.equal(out.record.presentation_snapshot.identity.run_id,'5DR-run');});
test('audited exception is preserved as exception with real timestamp',async()=>{const out=await canonicalRead({engine:'EDGE_STOCKS',run_id:'EDGE_STOCKS-run'},adapters({EDGE_STOCKS:adapter(record('EDGE_STOCKS','SELECTED','EXCEPTION_CANONICAL'))}));assert.equal(out.ok,true);if(out.ok){assert.equal(out.record.canonical_type,'EXCEPTION_CANONICAL');assert.equal(out.record.canonical_timestamp,'2026-09-28T10:05:00+05:30');}});
test('missing fails closed without latest-state substitution',async()=>{const out=await canonicalRead({engine:'IPO_EDGE',trading_date:'2026-09-27'},adapters({IPO_EDGE:adapter(null)}));assert.deepEqual(out,{ok:false,engine:'IPO_EDGE',reason:'NOT_FOUND',detail:'No exact canonical matched the requested engine and selector'});});
for(const state of ['SUPERSEDED','REJECTED'] as const)test(`${state} candidate stays auditable but cannot become selected canonical`,async()=>{const out=await canonicalRead({engine:'EDGE_STOCKS',run_id:'EDGE_STOCKS-run'},adapters({EDGE_STOCKS:adapter(record('EDGE_STOCKS',state))}));assert.equal(out.ok,false);if(!out.ok)assert.equal(out.reason,'NON_SELECTED');});
test('presentation identity mismatch fails closed',async()=>{const bad={...record('5DR'),presentation_snapshot:buildPresentationSnapshot({engine:'5DR',run_id:'other',result_id:'5DR-result',checkpoint_id:'5DR-cp',governance_state:'SELECTED',sections:[{name:'summary'}],source_payload_hash:'s'})};const out=await canonicalRead({engine:'5DR',run_id:'5DR-run'},adapters({5DR:adapter(bad)}));assert.equal(out.ok,false);if(!out.ok)assert.equal(out.reason,'IDENTITY_MISMATCH');});
test('one engine store failure cannot block the other two reads',async()=>{const failing:CanonicalReadAdapter=async()=>{throw new Error('forced')};const out=await canonicalReadIndependent([{engine:'5DR',run_id:'5DR-run'},{engine:'EDGE_STOCKS',run_id:'EDGE_STOCKS-run'},{engine:'IPO_EDGE',run_id:'IPO_EDGE-run'}],adapters({EDGE_STOCKS:failing}));assert.equal(out[0]?.ok,true);assert.equal(out[1]?.ok,false);assert.equal(out[2]?.ok,true);if(!out[1]?.ok)assert.equal(out[1].reason,'STORE_UNAVAILABLE');});
