import test from 'node:test';import assert from 'node:assert/strict';import {classifyVisionFailure,probeVisionReadiness,validateVisionObservation,VISION_MODEL} from '../src/vision-producer';

test('accepts governed verified screenshot extraction',()=>{const r=validateVisionObservation({category:'PRICE_TECHNICALS',verification:'VERIFIED',findings:[{label:'visible_last_price',value:25100,confidence:.94}],limitations:[]},'PRICE_TECHNICALS');assert.equal(r?.verification,'VERIFIED');assert.equal(r?.model,VISION_MODEL)});
test('rejects wrong screenshot category',()=>{assert.equal(validateVisionObservation({category:'DERIVATIVES_OI',verification:'VERIFIED',findings:[{label:'x',value:1,confidence:.9}],limitations:[]},'PRICE_TECHNICALS'),null)});
test('rejects confidence outside governed range',()=>{assert.equal(validateVisionObservation({category:'PRICE_TECHNICALS',verification:'VERIFIED',findings:[{label:'x',value:1,confidence:2}],limitations:[]},'PRICE_TECHNICALS'),null)});
test('verified extraction cannot be empty',()=>{assert.equal(validateVisionObservation({category:'PRICE_TECHNICALS',verification:'VERIFIED',findings:[],limitations:[]},'PRICE_TECHNICALS'),null)});
test('unavailable extraction may be empty with limitation',()=>{const r=validateVisionObservation({category:'DERIVATIVES_OI',verification:'UNAVAILABLE',findings:[],limitations:['not legible']},'DERIVATIVES_OI');assert.equal(r?.verification,'UNAVAILABLE')});
test('classifies Meta licence gate without leaking provider error',()=>{assert.equal(classifyVisionFailure(new Error('Workers AI error 5016 model agreement missing')),'LICENSE_NOT_ACCEPTED')});
test('classifies rate limiting',()=>{assert.equal(classifyVisionFailure(new Error('HTTP 429 rate limit exceeded')),'RATE_LIMITED')});
test('vision readiness probe reports ready when inference is accepted',async()=>{const calls:unknown[]=[];const ai={run:async(model:string,input:Record<string,unknown>)=>{calls.push({model,input});return {response:'READY'}}};const r=await probeVisionReadiness(ai);assert.equal(r.ok,true);assert.equal(r.status,'READY');assert.equal(calls.length,1)});
test('vision readiness probe reports licence blocker',async()=>{const ai={run:async()=>{throw new Error('5016 Model agreement has not been accepted')}};const r=await probeVisionReadiness(ai);assert.equal(r.ok,false);assert.equal(r.status,'LICENSE_NOT_ACCEPTED')});
